/******************************************************************************
      Filename    : PROCESS.C
      Product     : NITPIC
      Description : Second most important module than handles parsing
      Created     : August 4, 1999 [11:39:21]
      Last Edit   : January 17, 2002
*******************************************************************************
                       Copyright (c) 2002 - M.Heyns
                           All rights reserved.
******************************************************************************/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include <ctype.h>
#include <malloc.h>
#include <io.h>

#include "general.h"
#include "pic_c.h"

char DidElse[MAXLEVELS];
char IF_CUT = 0;
char IF_NOCUT = 0;
int FlagVariable, FlagCounter;
int do_arc = 0;

#define DEFAULT ""
static char cfgname[L_FLDLEN];

// finds the LAST occurance of a substring - else NULL
char *strrstr(char *buf, char *str)
{
        char *ptr = strstr(buf, str);           // find first

        while (strstr(ptr+1, str))              // find others
                ptr = strstr(ptr+1, str);
                
        return(ptr);
}

show_help()
{
        printf("\nSyntax: %s infile [/CPU=nnnnn] [switches]\n", PROGID);
        printf("\nSwitches: /A  = Generate Assembler (.ASM) file\n");
        printf("          /B  = Generate archiver BATCH file\n");
        printf("          /C  = Generate emulator (.COD) file (enables /L)\n");
        printf("          /F  = Write fuse information to .HEX file\n");
        printf("          /L  = Generate List (.LST) file\n");
        printf("          /M  = Generate Map (.MAP) file\n");
        printf("          /Q  = Quiet mode: Do not show progress\n");
        printf("          /S  = Saves the new settings into NITPIC.CFG\n");
        printf("        nnnnn = One of the CPU names from the NITPIC.INI file\n");
        printf("\n[Append '-' to disable a switch which was enabled in NITPIC.CFG]\n");
        printf("\nExample: %s MYSRC.NP /CPU=PIC16C54 /M /L /B- /Q\n", PROGID);
        unlink(ERRFILE);
        unlink(TMPFILE);
        printf("--- Press any key to continue ---\n");
        getch();
}

open_arc()
{
        if (!arc)
        {
                arc = fopen("ARC.BAT", "wt");
                if (arc)
                {
                        fprintf(arc, ":: - NITPIC Auto-archiving batch file -\n");
                        fprintf(arc, "::   To use:    ARC pathname\n");
                        fprintf(arc, "::   with 'pathname' the name of the archive directory\n");
                        fprintf(arc, "@echo off\n");
                }
        }
}

ReplaceCFG(char *cfgfile)
{
	FILE *fp;

	if (!(fp = fopen(cfgfile, "wt")))
	{
        	error("Error : Configuration file '%s' cannot be opened for re-creation\n", cfgname);
         	return;
	}

	fprintf(fp, ";******************************************************************************\n");
	fprintf(fp, ";     Filename    : NITPIC.CFG\n");
	fprintf(fp, ";     Product     : NITPIC\n");
	fprintf(fp, ";     Description : This file contains the DEFAULT parameters for NITPIC\n");
	fprintf(fp, ";******************************************************************************\n");
	fprintf(fp, ";                      Copyright (c) 2002 - M.Heyns\n");
	fprintf(fp, ";                          All rights reserved.\n");
	fprintf(fp, ";******************************************************************************\n");
	fprintf(fp, ";\n");
	fprintf(fp, ";  NOTE:  This file was generated by the compiler (see the /S option).\n");
	fprintf(fp, ";\n");
	fprintf(fp, ";------------------------------------------------------------------------------\n");
	fprintf(fp, "; NOTE: Command-line parameters always override these default settings !!!\n");
	fprintf(fp, ";------------------------------------------------------------------------------\n");
	fprintf(fp, ";ARC=      'YES' or 'NO' to enable or disable generation of ARC.BAT\n");
	fprintf(fp, ";MAP=      'YES' or 'NO' to enable or disable generation of NITPIC.MAP\n");
	fprintf(fp, ";LIST=     'YES' or 'NO' to enable or disable generation of .LST file\n");
	fprintf(fp, ";SIM=      'YES' or 'NO' to enable or disable generation of .SIM file\n");
	fprintf(fp, ";QUIET=    'YES' or 'NO' to enable or disable quiet mode (no display)\n");
	fprintf(fp, ";FUSES=    'YES' or 'NO' to enable or disable fuses inside .HEX file\n");
	fprintf(fp, ";CPU=      As you would specify on the command line.\n");
	fprintf(fp, ";------------------------------------------------------------------------------\n");
	fprintf(fp, "\n");
	fprintf(fp, "ARC=%s\n", 	do_arc == 1 			? "YES" : "NO");
	fprintf(fp, "MAP=%s\n", 	OPTIONS & O_domap 		? "YES" : "NO");
	fprintf(fp, "LIST=%s\n", 	OPTIONS & O_dolist 		? "YES" : "NO");
	fprintf(fp, "COD=%s\n", 	OPTIONS & O_docod 		? "YES" : "NO");
	fprintf(fp, "QUIET=%s\n", 	OPTIONS & O_verbatum 	? "NO"  : "YES");
	fprintf(fp, "FUSES=%s\n", 	do_fuses == 1 			? "YES" : "NO");
	fprintf(fp, "CPU=%s\n", 	CPU);
	fprintf(fp, "\n");
	fprintf(fp, ";******************************************************************************\n");
	fprintf(fp, ";                            End of NITPIC.CFG\n");
	fprintf(fp, ";*****************************************************************************/\n");

	fclose(fp);

	printf("*** NOTE: NITPIC.CFG was updated ***\n");
}

INITIALISE(int argc, char *argv[], char *IniFile)
{
        int i, j, k, RC = 0;
        char *ptr, *comma;
        char replace_cfg = 0;

        strcpy(cfgname, argv[0]);
        ptr = strrchr(cfgname, '.');
        if (ptr)
                strcpy(ptr, ".CFG");
        else
                strcat(cfgname, ".CFG");

        if (OpenINIfile(cfgname) == RC_OK)
        {
                if ((ptr = GetINIvalue(DEFAULT, "MAP")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                OPTIONS |= O_domap;
                }
                if ((ptr = GetINIvalue(DEFAULT, "LIST")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                OPTIONS |= O_dolist;
                }
                if ((ptr = GetINIvalue(DEFAULT, "ASM")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                OPTIONS |= O_doasm;
                }
                if ((ptr = GetINIvalue(DEFAULT, "COD")))
                {
                        if (stricmp(ptr, "YES") == 0)
                        {
                                OPTIONS |= O_docod;
                                OPTIONS |= O_dolist;
                        }
                }
                if ((ptr = GetINIvalue(DEFAULT, "QUIET")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                OPTIONS &= ~O_verbatum;
                }
                if ((ptr = GetINIvalue(DEFAULT, "ARC")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                do_arc = 1;
                }
                if ((ptr = GetINIvalue(DEFAULT, "FUSES")))
                {
                        if (stricmp(ptr, "YES") == 0)
                                do_fuses = 1;
                }
                if ((ptr = GetINIvalue(DEFAULT, "CPU")))
                {
                        strncpy(CPU, ptr, CPULEN-1);
                }

                if (CloseINIfile() != RC_OK)
                {
                        error("Error   %s - : Configuration file '%s' cannot be closed\n", HelpFile, cfgname);
                        exit(1);
                }
        }
        
        // read switches
        OPTIONS |= O_verbatum;          // by default line number display
        for (i = 1; i < argc; i++)
        {
                if (strnicmp(argv[i], "/CPU=", 5) == 0 && strlen(argv[i]) < 15)
                {
                        strcpy(CPU, &argv[i][5]);
                }

                else if (stricmp(argv[i], "/S") == 0)
                {
                        replace_cfg = 1;
                }

			// ON switches..........
                
                else if (stricmp(argv[i], "/M") == 0)
                {
                        OPTIONS |= O_domap;
                }
                else if (stricmp(argv[i], "/L") == 0)
                {
                        OPTIONS |= O_dolist;
                }
                else if (stricmp(argv[i], "/A") == 0)
                {
                        OPTIONS |= O_doasm;
                }
                else if (stricmp(argv[i], "/C") == 0)
                {
                        OPTIONS |= O_docod;
                        OPTIONS |= O_dolist;
                }
                else if (stricmp(argv[i], "/Q") == 0)
                {
                        OPTIONS &= ~O_verbatum;
                }
                else if (stricmp(argv[i], "/B") == 0)
                {
                        do_arc = 1;
                }
                else if (stricmp(argv[i], "/F") == 0)
                {
                        do_fuses = 1;
                }

			// OFF switches.........
                
                else if (stricmp(argv[i], "/M-") == 0)
                {
                        OPTIONS &= ~O_domap;
                }
                else if (stricmp(argv[i], "/L-") == 0)
                {
                        OPTIONS &= ~O_dolist;
                        OPTIONS &= ~O_docod;
                }
                else if (stricmp(argv[i], "/A-") == 0)
                {
                        OPTIONS &= ~O_doasm;
                }
                else if (stricmp(argv[i], "/C-") == 0)
                {
                        OPTIONS &= ~O_docod;
                }
                else if (stricmp(argv[i], "/Q-") == 0)
                {
                        OPTIONS |= O_verbatum;
                }
                else if (stricmp(argv[i], "/B-") == 0)
                {
                        do_arc = 0;
                }
                else if (stricmp(argv[i], "/F-") == 0)
                {
                        do_fuses = 0;
                }
                else if (argv[i][0] == '/')
                {
                        printf("ERROR> Unknown command line option: %s\n", argv[i]);
                        RC = 1; //fail - see below
                }
        }

		// replace the .CFG file
        if (replace_cfg == 1)
        	ReplaceCFG(cfgname);

        if (do_arc)
                open_arc();
        strupr(CPU);

        if (RC != 0)
        {
                show_help();
                exit(1);
        }
        
        if (!CPU[0])
        {
                error("Error   %s - : You MUST specify the CPU type using the '/CPU=nnnnnn' parameter\n", HelpFile);
                show_help();
                exit(1);
        }

        if (OpenINIfile(IniFile) != RC_OK)
        {
                error("Error   %s - : Initialisation file '%s' cannot be opened\n", HelpFile, IniFile);
                exit(1);
        }

        if (!(ptr = GetINIvalue(CPU, "CodeWidth")))
        {
                cannot_be_read("CodeWidth");
                exit(1);
        }
        
        CodeWidth = atoi(ptr);
        if (CodeWidth != 12 && CodeWidth != 14)
        {
                error("Error   %s - : Only 12 and 14 bit instructions supported\n", HelpFile);
                exit(1);
        }

        if (!(ptr = GetINIvalue(CPU, "FuseAddress")))
        {
                cannot_be_read("FuseAddress");
                exit(1);
        }
        FuseAddress = atoi(ptr);

        if (!(ptr = GetINIvalue(CPU, "IDaddress")))
        {
                cannot_be_read("IDaddress");
                exit(1);
        }
        IDaddress = atoi(ptr);

        if (!(ptr = GetINIvalue(CPU, "ResetVector")))
        {
                cannot_be_read("ResetVector");
                exit(1);
        }
        ResetVector = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "INTvector")))
        {
                cannot_be_read("INTvector");
                exit(1);
        }
        INTvector = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "TopROM")))
        {
                cannot_be_read("TopROM");
                exit(1);
        }
        TopROM = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "StackDepth")))
        {
                cannot_be_read("StackDepth");
                exit(1);
        }
        StackDepth = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "TopCodePage")))
        {
                cannot_be_read("TopCodePage");
                exit(1);
        }
        TopCodePage = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "CodePageSize")))
        {
                cannot_be_read("CodePageSize");
                exit(1);
        }
        CodePageSize = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "ProcRange")))
        {
                cannot_be_read("ProcRange");
                exit(1);
        }
        ProcRange = atoi(ptr);
        
        if (!(ptr = GetINIvalue(CPU, "DataPageSize")))
        {
                cannot_be_read("DataPageSize");
                exit(1);
        }
        DataPageSize = atoi(ptr);
        
        if ((ptr = GetINIvalue(CPU, "Reg")))
        {
                do
                {
                        if ((comma = strchr(ptr, ',')))
                                *comma = '\0';
                        Reg[NextReg] = new(strlen(ptr)+1);
                        strcpy(Reg[NextReg], ptr);
                        comma++;
                        RegAddr[NextReg] = atoi(comma);
                        if (RegAddr[NextReg] >= DataPageSize)
                                TwoOrMorePages = 1;
                        NextReg++;
                } while ((ptr = GetNEXTvalue()) && NextReg < MAXCPUREG);
        }
        else
        {
                cannot_be_read("Reg");
                exit(1);
        }

        if ((ptr = GetINIvalue(CPU, "UserReg")))
        {
                do
                {
                        if ((comma = strchr(ptr, ',')))
                                *comma = '\0';
                        UserRegStart[NextRegBank] = atoi(ptr);
                        comma++;
                        UserRegEnd[NextRegBank++] = atoi(comma);
                } while ((ptr = GetNEXTvalue()) && NextRegBank < MAXREGBANKS);
        }
        else
        {
                cannot_be_read("UserReg");
                exit(1);
        }

        if ((ptr = GetINIvalue(CPU, "AllBanks")))
        {
                do
                {
                        if ((comma = strchr(ptr, ',')))
                                *comma = '\0';
                        AllBanksStart[NextAll] = atoi(ptr);
                        comma++;
                        AllBanksEnd[NextAll++] = atoi(comma);
                } while ((ptr = GetNEXTvalue()) && NextAll < MAXREGBANKS);
        }

        if (CloseINIfile() != RC_OK)
        {
                error("Error   %s - : Initialisation file '%s' cannot be closed\n", HelpFile, IniFile);
                exit(1);
        }

        // determine user register bank sizes
        for (i = 0; i < MAXREGBANKS; i++)
        {
                if (UserRegEnd[i] > UserRegStart[i])
                {
                        BankSize[i] = UserRegEnd[i] - UserRegStart[i] + 1;
                        MaxVariables += BankSize[i];
                }
        }

        // pre-calculate the user variable addresses
        j = 0;  // index to variables table
        for (i = 0; i < MAXREGBANKS; i++)
        {
                for (k = UserRegStart[i]; k <= UserRegEnd[i]; k++)
                {
                        VarAddr[j] = k;
                        if (VarAddr[j] >= DataPageSize)
                                TwoOrMorePages = 1;
                        j++;
                }
        }
}

cannot_be_read(char *name)
{
        error("Error   %s - : '%s' cannot be read from NITPIC.INI\n", HelpFile, name);
}

do_toptest()
{
        int i;
        
        for (i = Level; i > 0; i--)
        {
                switch (BlockType[i])
                {
                
                        case BIF:
                                error("Error[LevelCheck]   %s %d : IF active on level %d\n", INFILE, NR, i); break;
                        case BFOR:
                                error("Error[LevelCheck]   %s %d : FOR active on level %d\n", INFILE, NR, i); break;
                        case BWHILE:
                                error("Error[LevelCheck]   %s %d : WHILE active on level %d\n", INFILE, NR, i); break;
                        case BREPEAT:
                                error("Error[LevelCheck]   %s %d : REPEAT active on level %d\n", INFILE, NR, i); break;
                        case BLOOP:
                                error("Error[LevelCheck]   %s %d : LOOP active on level %d\n", INFILE, NR, i); break;
                        default: break;
                }
        }
}

char *HeaderLabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_%d_%d_HEAD", Level, Sequence[Level]);
        return(buf);
}

char *StartLabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_%d_%d_START", Level, Sequence[Level]);
        return(buf);
}

char *EndLabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_%d_%d_END", Level, Sequence[Level]);
        return(buf);
}

char *ORlabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_OR_%d", ORlabelCount);
        return(buf);
}

char *IF_ELSE_ENDlabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_IEE_%d_%d", Level, IEElabelCount[Level]);
        return(buf);
}

char *JmpLabel()
{
        static char buf[L_FLDLEN];
        sprintf(buf, "L_%d_JMP", JmpLabelCount);
        return(buf);
}

char *start_of(char ptr[])
{
        int i = 0;

        while (ptr[i] == ' ' || ptr[i] == '\t')
                i++;
        return(&ptr[i]);
}

cut_trails(char ptr[])
{
        int index;
        
        // remove trailing blanks
        index = strlen(ptr) - 1;        // point to last char
        while (index && isspace(ptr[index])) 
                index--;
        ptr[index+1] = '\0';

        if (!ptr[index])                // if index == 0
                ptr[index] = '\0';      // kill while string
}

define_byte(char *name)
{
        int len, i;
        char *ptr;
        char *buf = new(L_FLDLEN);
        
        if (NextVar == MaxVariables || NextVar == MAXVARS)
        {
                error("Error   %s %d : Too many variables for this CPU\n", INFILE, NR);
                free(buf);
                return;
        }
        
        if ((ptr = strchr(name, '[')))
        {
                if (name[strlen(name)-1] != ']')
                {
                        error("Error   %s %d : Array declaration syntax error\n", INFILE, NR);
                        free(buf);
                        return;
                }
                len = get_value(ptr+1);
                if (NextVar+len > MaxVariables || NextVar+len >= MAXVARS)
                {
                        error("Error   %s %d : Too many variables for this CPU\n", INFILE, NR);
                        free(buf);
                        return;
                }
                *ptr = '\0';
                for (i = 0; i < len; i++)
                {
                        sprintf(buf, "%s[%d]", name, i);
                        Variable[NextVar] = new(strlen(buf)+1);
                        strcpy(Variable[NextVar], buf);
                        if (i > 0 && VarAddr[NextVar] > VarAddr[NextVar-1] + 1)
                                error("Error   %s %d : Array '%s' spans 2 data pages at index %d\n", INFILE, NR, name, NextVar);
                        NextVar++;
                }
        }
        else
        {
                Variable[NextVar] = new(strlen(name)+1);
                strcpy(Variable[NextVar], name);
                NextVar++;
        }
        free(buf);
}

define_define(char *Line, char *Token)
{
        int i;
        char *ptr;
 
        if (NextDef < MAXMACS)
        {
                for (i = 0; i < NextDef; i++)
                {
                        if (strcmp(DefName[i], Token) == 0)
                        {
                                error("Error   %s %d : '%s' already defined\n", INFILE, NR, Token);
                                return;
                        }
                }
                if (find_reg(Token) >= 0)
                {
                        error("Error   %s %d : Reserved word '%s' used in '#define'\n", INFILE, NR, Token);
                        return;
                }

                DefName[NextDef] = new(strlen(Token) + 1);
                strcpy(DefName[NextDef], Token);

                ptr = strstr(Line, DefName[NextDef]);
                ptr += strlen(DefName[NextDef]);
                while (*ptr && isspace(*ptr)) ptr++;

                Define[NextDef] = new(strlen(ptr) + 1);
                strcpy(Define[NextDef], ptr);
                NextDef++;
                return;
        }
        else
        {
                error("Error   %s %d : '#define' limit exceeded\n", INFILE, NR);
        }
}

do_lookups()
{
        int i, j;

        if (NextLookup > 0)
        {
                for (i = 0; i < NextLookup; i++)
                {
                        strcpy(S[0], LookupTbl[i]);
                        fracture();
                        new_proc(S[2]);

                        if (CodeWidth == 12)
                        {
                                Opcode("pcl_addwf", 2, 1, S[2]);
                        }
                        else
                        {
                                Opcode("fix_pclath", 0, 0, "");
                                Opcode("addwf", 2, 1, "");
                        }
                        for (j = 3; j <= NF; j++)
                                Opcode("retlw", get_value(S[j]), 0, "");

                        strcpy(S[0], "endproc");
                        fracture();
                        do_endproc();
                        free(LookupTbl[i]);
                }
                NextLookup = 0;
        }
}

void LINE()
{
        char *buf = new(L_FLDLEN);
        char *ptr, *end, *tmp;
        int i, j, k;
        unsigned int val;
        char temp[5];

        // replace tabs with spaces - AND REMOVE '\n' AT THE END
        for (i = 0; i < strlen(S[0]); i++)
        {
                if (isspace(S[0][i]))
                        S[0][i] = ' ';
        }

        // replace quoted characters with numerical values
        end = S[0];
        while ((ptr = strchr(end, 0x27)))
        {     // find first quote
                if (*(ptr+2) == 0x27)
                {         // get second quote
                        sprintf(temp, "%3.3d", *(ptr+1));
                        *ptr++ = temp[0];
                        *ptr++ = temp[1];
                        *ptr   = temp[2];
                }
                end = ++ptr;
        }

        // remove and add spaces to assist with compile process later on
        while (replace(S[0], "=", " @ "));      // make all '='s -> '@'
        while (replace(S[0], "+ @ ", " +@ "));
        while (replace(S[0], "- @ ", " -@ "));
        while (replace(S[0], "& @ ", " &@ "));
        while (replace(S[0], "| @ ", " |@ "));
        while (replace(S[0], "^ @ ", " ^@ "));
        while (replace(S[0], "< @ ", " <@ "));
        while (replace(S[0], "> @ ", " >@ "));
        while (replace(S[0], "! @ ", " !@ "));
        while (replace(S[0], "! &@ ", " !&@ "));
        while (replace(S[0], "! |@ ", " !|@ "));
        while (replace(S[0], "! ^@ ", " !^@ "));
        while (replace(S[0], "@", "="));        // make all '@' -> '='
        while (replace(S[0], "  ", " "));
        while (replace(S[0], " >>", ">>"));
        while (replace(S[0], " <<", "<<"));
        while (replace(S[0], " ++", "++"));
        while (replace(S[0], " --", "--"));
        while (replace(S[0], "& ", "&"));
        while (replace(S[0], " (", "("));
        while (replace(S[0], "( ", "("));
        while (replace(S[0], " )", ")"));
        while (replace(S[0], " )", ")"));
        while (replace(S[0], " [", "["));
        while (replace(S[0], "[ ", "["));
        while (replace(S[0], " ]", "]"));
        while (replace(S[0], " ]", "]"));

        // do hard-coded 'high' / 'low' replacements
        while ((ptr = strstr(S[0], "high(")) || (ptr = strstr(S[0], "HIGH(")))
        {
                if (isdigit(ptr[5]))
                {
                        tmp = new(L_FLDLEN);
                        strcpy(tmp, ptr);
                        end = strchr(tmp, ')');
                        end[1] = '\0';
                        val = get_value(&tmp[5]) >> 8;
                        sprintf(buf, "%u", val);
                        replace(ptr, tmp, buf);
                        free(tmp);
                }
                else
                {
                        replace(ptr, ")", "");
                        replace(ptr, "high(", "_H_");
                        replace(ptr, "HIGH(", "_H_");
                }
        }
        while ((ptr = strstr(S[0], "low(")) || (ptr = strstr(S[0], "LOW(")))
        {
                if (isdigit(ptr[4]))
                {
                        tmp = new(L_FLDLEN);
                        strcpy(tmp, ptr);
                        end = strchr(tmp, ')');
                        end[1] = '\0';
                        val = get_value(&tmp[4]) & 0xff;
                        sprintf(buf, "%u", val);
                        replace(ptr, tmp, buf);
                        free(tmp);
                }
                else
                {
                        replace(ptr, ")", "");
                        replace(ptr, "low(", "_L_");
                        replace(ptr, "LOW(", "_L_");
                }
        }

        // fracture the line for the first time
        cut_trails(S[0]);       // remove trailing blanks
        fracture();

        // filter out compiler-specifics
        if (S[1][0] == '#' && S[1][1] == '#')
        {
                if (strcmp(&S[1][2], CPU) == 0)
                {
                        ptr = strchr(S[0], '#');
                        strcpy(S[0], ptr + strlen(CPU)+3);      //+3 for ## and space
                        fracture();
                }
                else
                {
                        free(buf);
                        return;         // ignore this line
                }
        }

        if (!NF)
        {
                free(buf);
                return;
        }
        else if (NF >= 1 && strncmp(S[1], "endproc", 7) == 0)
        {
                if (SkipTillEnd)
                {
                        SkipTillEnd = 0;
                        free(buf);
                        return;
                }
        }
        else if (SkipTillEnd)
        {
                free(buf);
                return;
        }

        if (NF == 1 && strcmp(S[1], "#else") == 0)
        {
                if (IF_CUT == 1 && IF_NOCUT == 0)
                {
                        IF_CUT = 0;
                        IF_NOCUT = 1;
                }
                else if (IF_CUT == 0 && IF_NOCUT == 1)
                {
                        IF_CUT = 1;
                        IF_NOCUT = 0;
                }
                else
                        error("Error   %s %d : '#else' out of place\n", INFILE, NR);
                free(buf);
                return;
        }
        else if (NF == 1 && strcmp(S[1], "#endif") == 0)
        {
                if (!IF_CUT && !IF_NOCUT)
                        error("Error   %s %d : '#endif' out of place\n", INFILE, NR);
                IF_CUT = 0;
                IF_NOCUT = 0;
                free(buf);
                return;
        }
        else if (IF_CUT == 1)
        {
                free(buf);
                return;                                         // throw EVERYTHING away
        }
        else if (NF == 2 && strcmp(S[1], "#ifdef") == 0)
        {
                if (IF_CUT || IF_NOCUT)
                {
                        error("Error   %s %d : Conditional compile already active\n", INFILE, NR);
                        free(buf);
                        return;
                }
                if (find_selection(S[2]))
                        IF_NOCUT = 1;
                else
                        IF_CUT = 1;
                free(buf);
                return;
        }
        else if (NF == 2 && strcmp(S[1], "#ifndef") == 0)
        {
                if (IF_CUT || IF_NOCUT)
                {
                        error("Error   %s %d : Conditional compile already active\n", INFILE, NR);
                        free(buf);
                        return;
                }
                if (!find_selection(S[2]))
                        IF_NOCUT = 1;
                else
                        IF_CUT = 1;
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#echo") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();
                
                printf("%s %d : %s\n", INFILE, NR, &S[0][6]);
                free(buf);
                return;
        }
        else if (NF > 2 && strcmp(S[1], "#macro") == 0)
        {
                if (NextMac < MAXMACS)
                {
                        for (i = 0; i < NextMac; i++)
                        {
                                if (strcmp(MacName[i], S[2]) == 0)
                                {
                                        error("Error   %s %d : Macro '%s' already defined\n", INFILE, NR, S[2]);
                                        free(buf);
                                        return;
                                }
                        }
                        if (find_reg(S[2]) >= 0)
                        {
                                error("Error   %s %d : Reserved word '%s' used for macro name\n", INFILE, NR, S[2]);
                                free(buf);
                                return;
                        }

                        MacName[NextMac] = new(strlen(S[2]) + 1);
                        strcpy(MacName[NextMac], S[2]);

                        ptr = strstr(S[0], MacName[NextMac]);
                        ptr += strlen(MacName[NextMac]);
                        while (*ptr && isspace(*ptr)) ptr++;

                        Macro[NextMac] = new(strlen(ptr) + 1);
                        strcpy(Macro[NextMac], ptr);
                        NextMac++;
                }
                else
                {
                        error("Error   %s %d : '#macro' limit exceeded\n", INFILE, NR);
                }
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#define") == 0)
        {
                define_define(S[0], S[2]);
                free(buf);
                return;
        }
        else if (NF > 2 && strcmp(S[1], "#redefine") == 0)
        {
                for (i = 0; i < NextDef; i++)
                {
                        if (strcmp(DefName[i], S[2]) == 0)
                        {
                                free(Define[i]);

                                ptr = strstr(S[0], S[2]);
                                ptr += strlen(S[2]);
                                while (*ptr && isspace(*ptr)) ptr++;
        
                                Define[NextDef] = new(strlen(ptr) + 1);
                                strcpy(Define[NextDef], ptr);
                                free(buf);
                                return;
                        }
                }
                define_define(S[0], S[2]);      // does not exist, define from scratch
                free(buf);
                return;
        }
        else if (NF == 2 && strcmp(S[1], "#touch") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();
                
                if ((k = find_reg(S[2])) >= 0)
                        VarUsed[k] = 1;         // flag as referenced
                else
                        Undefined(S[2]);
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#use") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();

                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                fracture();
                for (i = 2; i <= NF; i++)
                {
                        // see if we have space to add the name
                        if ((Licensed > 0 && NextLib >= MAXPROCS) ||
                            (!Licensed && NextLib >= DEMOMAXPROCS))
                        {
                                error("Error   %s %d : Procedure limit exceeded\n", INFILE, NR);
                                free(buf);
                                return;
                        }

                        // simply remember name
                        LibName[NextLib] = new(strlen(S[i]) + 1);
                        strcpy(LibName[NextLib], S[i]);
                        NextLib++;
                }
                
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#lookup") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();
                
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                while ((ptr = strchr(S[0], '\\'))) *ptr = ' ';
                if (INTvector >= 0 && !int_declared)
                {
                        LookupTbl[NextLookup] = new(strlen(S[0]) + 1);
                        strcpy(LookupTbl[NextLookup], S[0]);
                        NextLookup++;
                }
                else
                {
                        fracture();
                        new_proc(S[2]);
                        if (CodeWidth == 12)
                        {
                                Opcode("pcl_addwf", 2, 1, S[2]);
                        }
                        else
                        {
                                Opcode("fix_pclath", 0, 0, "");
                                Opcode("addwf", 2, 1, "");
                        }
                        for (i = 3; i <= NF; i++)
                                Opcode("retlw", get_value(S[i]), 0, "");

                        strcpy(S[0], "endproc");
                        fracture();
                        do_endproc();
                }
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#hex_direct") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();
                
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                while ((ptr = strchr(S[0], '\\'))) *ptr = ' ';
                fracture();
                j = get_value(S[2]);    // get address
                for (i = 3; i <= NF; i++)
                {
                        if (NextHex < MAXHEXDIRECT - 1)
                        {
                                HexAddress[NextHex] = j;
                                HexData[NextHex] = get_value(S[i]);
                                j += 2;
                                NextHex++;
                        }
                        else
                        {
                                error("Error   %s %d : Too many direct parameters to .HEX file\n", INFILE, NR);
                                continue;
                        }
                }
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "jump") == 0)
        {
                // perform define and macro replacements
                do_defs_macs();
                
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                while ((ptr = strchr(S[0], '\\'))) *ptr = ' ';
                fracture();

                if (isdigit(S[2][0]) && get_value(S[2]) <= 255)
                {
                        Opcode("movlw", get_value(S[2]), 0, "");
                        if (CodeWidth == 12)
                        {
                                Opcode("pcl_addwf", 2, 1, S[2]);
                        }
                        else
                        {
                                Opcode("fix_pclath", 0, 0, "");
                                Opcode("addwf", 2, 1, "");
                        }
                }
                else if (is_proc(S[2]))
                {
                        do_call(S[2]);
                        if (CodeWidth == 12)
                        {
                                Opcode("pcl_addwf", 2, 1, S[2]);
                        }
                        else
                        {
                                Opcode("fix_pclath", 0, 0, "");
                                Opcode("addwf", 2, 1, "");
                        }
                }
                else if (find_reg(S[2]))
                {
                        setpage(S[2]);
                        Opcode("movf", find_reg(S[2]), 0, "");
                        if (CodeWidth == 12)
                        {
                                Opcode("pcl_addwf", 2, 1, S[2]);
                        }
                        else
                        {
                                Opcode("fix_pclath", 0, 0, "");
                                Opcode("addwf", 2, 1, "");
                        }
                }
                else
                {
                        error("Error   %s %d : Only CONSTANTS or BYTES allowed\n", INFILE, NR);
                        free(buf);
                        return;
                }

                // build jump table
                for (i = 3; i <= NF; i++)
                {
                        if (busy_with_proc >= 0)
                        {
                                sprintf(buf, "%s%d", S[i], busy_with_proc);
                                Opcode("goto", 0, 0, buf);
                        }
                        else
                                Opcode("goto", 0, 0, S[i]);
                }
                free(buf);
                return;
        }

        CleanLine();
        free(buf);
}

do_defs_macs()
{
        int DidChanges = 0;
        
        while (do_defines()) DidChanges = 1;
        while (!strchr(S[0], '\\') && do_macros()) DidChanges = 1;
        while (do_defines()) DidChanges = 1;

        if (DidChanges)
        {
                if (!no_list && ((OPTIONS & O_dolist) || (OPTIONS & O_doasm)))
                {
                        fprintf(tmp, "%5d: %s\n", NR, start_of(S[0]));
                        tmp_index++;
                }
        }
}

CleanLine()
{
        char *tmp1;
        char *buf = new(L_FLDLEN);
        char *ptr, *end;
        int i, j, addr, val1;
        unsigned int val;
        static char temp[40];
        char *savedS0;

        // perform define and macro replacements
        do_defs_macs();
                
        // process S[0] either in pieces or as a whole
        if ((ptr = strchr(S[0], '\\')) && !isalpha(*(ptr+1)))
        {
                savedS0 = new(strlen(S[0]) + 1);
                strcpy(savedS0, S[0]);          // save it away
                ptr = savedS0;                  // starting point
                while ((end = strchr(ptr, '\\')))
                {
                        strncpy(S[0], ptr, end - ptr);
                        S[0][end-ptr] = '\0';
                        CleanLine();            // process partly
                        ptr = ++end;            // look at next section
                }
                strcpy(S[0], ptr);
                CleanLine();
                free(savedS0);
                free(buf);
                return;
        }

        // line is clean - so let's proceed
        fracture();
        
        // test switches
        if (NF == 2 && strcmp(S[1], "#include") == 0)
        {
                if (infile(S[2]) == RC_FAIL)
                        error("Error   %s %d : Cannot read '%s'\n", INFILE, NR, S[2]);

                // take note of this for list file
                if (!no_list && ((OPTIONS & O_dolist) || (OPTIONS & O_doasm)))
                {
                        fprintf(tmp, "---[ Back to %s ]---\n", INFILE);
                        tmp_index++;
                }
                
                free(buf);
                return;
        }
        else if (NF == 1 && strcmp(S[1], "#toptest") == 0)
        {
                do_toptest();
                free(buf);
                return;
        }
        else if (NF == 1 && stricmp(S[1], "#list_off") == 0)
        {
                no_list = 1;
                free(buf);
                return;
        }
        else if (NF == 1 && stricmp(S[1], "#list_on") == 0)
        {
                no_list = 0;
                free(buf);
                return;
        }
        else if (NF >= 2 && stricmp(S[1], "#fuse_addr") == 0)
        {
                if (NF > 2)
                        warning("Warning %s %d : Extra parameters ignored\n", INFILE, NR);
                FuseAddress = get_value(S[2]);
                free(buf);
                return;
        }
        else if (NF >= 2 && stricmp(S[1], "#id_addr") == 0)
        {
                if (NF > 2)
                        warning("Warning %s %d : Extra parameters ignored\n", INFILE, NR);
                IDaddress = get_value(S[2]);
                free(buf);
                return;
        }
        else if (NF >= 2 && stricmp(S[1], "#fuses") == 0)
        {
                if (!do_fuses)
                {
                        warning("Warning %s %d : Fuses specified but not used - (see /F switch)\n", INFILE, NR);
                        // used by assemblers though
                }
                if (NF > 2)
                        warning("Warning %s %d : Extra parameters ignored\n", INFILE, NR);
                FUSES = get_value(S[2]);
                did_fuses = 1;
                free(buf);
                return;
        }
        else if (NF >= 2 && stricmp(S[1], "#id") == 0)
        {
                if (NF > 2)
                        warning("Warning %s %d : Extra parameters ignored\n", INFILE, NR);
                PID = get_value(S[2]);
                did_id = 1;
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#bit") == 0)
        {
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                fracture();
                for (i = 2; i <= NF; i++)
                {
                        if (!isalpha(S[i][0]) && (S[i][0] != '_'))
                        {
                                error("Error   %s %d : '%s': Variable names must begin with A-Z,a-z or '_'\n", INFILE, NR, S[i]);
                                continue;
                        }

                        if (FlagCounter == 0)
                        { // the first bit being used
                                sprintf(buf, "_Flags%d_", FlagVariable);
                                define_byte(buf);
                        }
                        sprintf(buf, "#define %s _Flags%d_:%d", S[i], FlagVariable, FlagCounter);
                        define_define(buf, S[i]);
                        FlagCounter++;
                        if (FlagCounter == 8)
                        {
                                FlagCounter = 0;
                                FlagVariable++;
                        }
                }
                free(buf);
                return;
        }
        else if (NF >= 2 && (strcmp(S[1], "#data") == 0 || strcmp(S[1], "#byte") == 0))
        {
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                fracture();
                for (i = 2; i <= NF; i++)
                {
                        if (!isalpha(S[i][0]) && (S[i][0] != '_'))
                        {
                                error("Error   %s %d : '%s': Variable names must begin with A-Z,a-z or '_'\n", INFILE, NR, S[i]);
                                continue;
                        }
                        if (find_reg(S[i]) >= 0)
                        {
                                error("Error   %s %d : '%s' already defined\n", INFILE, NR, S[i]);
                                continue;
                        }
                        for (j = 0; j < NextDef; j++)
                        {
                                if (strcmp(DefName[j], S[i]) == 0)
                                {
                                        error("Error   %s %d : '%s' already used by '#define'\n", INFILE, NR, S[i]);
                                        free(buf);
                                        return;
                                }
                        }
                        define_byte(S[i]);
                }
                free(buf);
                return;
        }
        else if (NF >= 2 && strcmp(S[1], "#word") == 0)
        {
                while ((ptr = strchr(S[0], ','))) *ptr = ' ';
                fracture();
                for (i = 2; i <= NF; i++)
                {
                        if (!isalpha(S[i][0]) && (S[i][0] != '_'))
                        {
                                error("Error   %s %d : '%s': Variable names must begin with A-Z,a-z or '_'\n", INFILE, NR, S[i]);
                                continue;
                        }
                        if (find_reg(S[i]) >= 0)
                        {
                                error("Error   %s %d : '%s' already defined\n", INFILE, NR, S[i]);
                                continue;
                        }
                        for (j = 0; j < NextDef; j++)
                        {
                                if (strcmp(DefName[j], S[i]) == 0)
                                {
                                        error("Error   %s %d : '%s' already used by '#define'\n", INFILE, NR, S[i]);
                                        free(buf);
                                        return;
                                }
                        }
                        if (strchr(S[i], '[') || strchr(S[i], ']'))
                        {
                                error("Error   %s %d : Only BYTE arrays allowed\n", INFILE, NR);
                                continue;
                        }
                        ptr = new(L_FLDLEN);
                        sprintf(ptr, "_H_%s", S[i]);
                        define_byte(ptr);
                        sprintf(buf, "_L_%s", S[i]);
                        define_byte(buf);
                        // look directly at byte addresses
                        if (VarAddr[NextVar-1] - VarAddr[NextVar-2] != 1)
                                error("Error   %s %d : '%s' crosses page boundaries - Move up/down\n", INFILE, NR, S[i]);
                        free(ptr);
                }
                free(buf);
                return;
        }
        else if (NF == 1 && strcmp(S[1], "break") == 0)
        {
                if (Level > 0)
                {
                        for (i = Level; i > 0; i--)
                        {
                                if (BlockType[i] == BWHILE || 
                                    BlockType[i] == BREPEAT ||
                                    BlockType[i] == BCOUNT ||
                                    BlockType[i] == BFOR ||
                                    BlockType[i] == BLOOP)
                                    {
                                        setpagenum(StartPage[Level]);
                                        sprintf(temp, "L_%d_%d_END", i, Sequence[i]);
                                        _JMP(temp);
                                        free(buf);
                                        return;
                                }
                        }
                }
                error("Error   %s %d : No control loop in effect\n", INFILE, NR);
                free(buf);
                return;
        }
        else if (NF == 1 && strcmp(S[1], "continue") == 0)
        {
                if (Level > 0)
                {
                        for (i = Level; i > 0; i--)
                        {
                                if (BlockType[i] == BWHILE || 
                                    BlockType[i] == BFOR ||
                                    BlockType[i] == BCOUNT ||
                                    BlockType[i] == BLOOP ||
                                    BlockType[i] == BREPEAT)
                                    {
                                        setpagenum(StartPage[Level]);
                                        sprintf(temp, "L_%d_%d_START", i, Sequence[i]);
                                        _JMP(temp);
                                        free(buf);
                                        return;
                                }
                        }
                }
                error("Error   %s %d : No control loop in effect\n", INFILE, NR);
                free(buf);
                return;
        }

        // Do 'IF'...'RETURN' construct
        else if (NF > 1 && strcmp(S[1], "if") == 0 && strncmp(S[NF], "return", 6) == 0)
        {
                ptr = strstr(S[0], "if");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;

                end = strstr(ptr, "return");
                end--;
                *end = '\0';
                
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BIF;

                do_exp(ptr, 1);

                strcpy(S[0], S[NF]);
                fracture();
                do_return();

                _Label(EndLabel());
                terminate_if_group();           // and synch data pages
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'IF'...'SET' construct
        else if (NF > 1 && strcmp(S[1], "if") == 0 && 
                           strcmp(S[NF-1], "set") == 0 &&
                           strcmp(S[NF], "then") != 0)
                           {
                ptr = strstr(S[0], "if");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;

                end = strstr(ptr, "set");
                if (strstr(end+1, "set"))
                        end = strstr(end+1, "set");     // find LAST set
                *end = '\0';
                
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BIF;

                do_exp(ptr, 1);

                if ((val1 = validate_bit(S[NF])) < 0)
                {
                        free(buf);
                        return;
                }
                setpage(S[NF]);
                Opcode("bsf", find_reg(S[NF]), val1, "");

                _Label(EndLabel());
                terminate_if_group();           // and synch data pages
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'IF'...'CLEAR' construct
        else if (NF > 1 && strcmp(S[1], "if") == 0 &&
                           strcmp(S[NF-1], "clear") == 0 &&
                           strcmp(S[NF], "then") != 0)
                           {
                ptr = strstr(S[0], "if");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;

                end = strstr(ptr, "clear");
                if (strstr(end+1, "clear"))
                        end = strstr(end+1, "clear");   // find LAST clear
                *end = '\0';
                
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BIF;

                do_exp(ptr, 1);

                if ((val1 = validate_bit(S[NF])) < 0)
                {
                        free(buf);
                        return;
                }
                setpage(S[NF]);
                Opcode("bcf", find_reg(S[NF]), val1, "");

                _Label(EndLabel());
                terminate_if_group();           // and synch data pages
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'IF'...'GOTO' construct
        else if (NF > 1 && strcmp(S[1], "if") == 0 && strcmp(S[NF-1], "goto") == 0)
        {
                if (strcmp(S[NF-2], "then") == 0)
                {
                        warning("Warning %s %d : 'THEN' redundant - ignored\n", INFILE, NR);
                        S[NF-2][0] = '\0';
                        rebuild();
                }

                // create a temporary buffer
                tmp1 = new(L_FLDLEN);

                // find split point
                end = strstr(S[0], "goto");
                *end = '\0';
                end++;

                // make two new lines
                strcpy(tmp1, end);              // 'goto ...'
                strcat(S[0], "then");   // 'if ..... then'

                // process 'if ....  then'
                CleanLine();

                // process 'goto ....'
                strcpy(S[0], "g");
                strcat(S[0], tmp1);
                CleanLine();

                // process 'endif'
                strcpy(S[0], "endif");
                CleanLine();

                // done with temporary buffer
                free(tmp1);
                free(buf);
                return;
        }

        // Do 'IF'... construct
        else if (NF > 1 && strcmp(S[1], "if") == 0 && strcmp(S[NF], "then") == 0)
        {
                ptr = strstr(S[0], "if");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;
                end = strrstr(ptr, "then");
                *end = '\0';
                
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BIF;
                ForceFix[Level] = 0;            // reset

                PrevPage[Level] = datapagenum;
                do_exp(ptr, 1);
                PrevPageChanged[Level] = PageChanged[Level];
                
                free(buf);
                return;
        }

        // Do 'ELSE IF'... construct
        else if (NF > 2 && strcmp(S[1], "else") == 0 && 
                 strcmp(S[2], "if") == 0 && strcmp(S[NF], "then") == 0)
                 {
                if (!Level || BlockType[Level] != BIF || DidElse[Level])
                {
                        error("Error   %s %d : 'else if' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }
                
                if (datapagenum != StartPage[Level])
                        ForceFix[Level] = 1;
                _JMP(IF_ELSE_ENDlabel());

                _Label(EndLabel());
                if (PrevPageChanged[Level])
                        reset_datapage();
                else
                        datapagenum = PrevPage[Level];

                BusyWithELSE[Level] = Yes;
                
                ptr = strstr(S[0], "if");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;
                end = strrstr(ptr, "then");
                *end = '\0';
                
                Sequence[Level]++;

                PrevPage[Level] = datapagenum;
                do_exp(ptr, 0);         // DO NOT REMEMBER ORG DATAPAGE !!!
                PrevPageChanged[Level] = PageChanged[Level];

                free(buf);
                return;
        }

        // Do 'ELSE'... construct
        else if (NF == 1 && strcmp(S[1], "else") == 0)
        {
                if (!Level || BlockType[Level] != BIF || DidElse[Level])
                {
                        error("Error   %s %d : 'else' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }
                
                if (datapagenum != StartPage[Level])
                        ForceFix[Level] = 1;
                _JMP(IF_ELSE_ENDlabel());

                _Label(EndLabel());
                if (PrevPageChanged[Level])
                        reset_datapage();
                else
                        datapagenum = PrevPage[Level];

                PrevPage[Level] = datapagenum;

                BusyWithELSE[Level] = Yes;
                DidElse[Level] = 1;             // YES
                
                Sequence[Level]++;
                free(buf);
                return;
        }

        // terminate if block
        else if (NF == 1 && strcmp(S[1], "endif") == 0)
        {
                if (!Level || BlockType[Level] != BIF)
                {
                        error("Error   %s %d : 'endif' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }
                
                if (datapagenum != StartPage[Level])
                        ForceFix[Level] = 1;
                        
                _Label(EndLabel());
                terminate_if_group();
                if (PrevPageChanged[Level])
                        reset_datapage();
                else
                        datapagenum = PrevPage[Level];

                if (ForceFix[Level])
                        reset_datapage();
                        
                BlockType[Level] = BNONE;
                DidElse[Level] = 0;             // NO
                Level--;
                free(buf);
                return;
        }

        // Do 'WHILE'... construct
        else if (NF > 1 && strcmp(S[1], "while") == 0 && strcmp(S[NF], "do") == 0)
        {
                ptr = strstr(S[0], "while");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;
                end = strrstr(ptr, "do");
                *end = '\0';
                
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BWHILE;
                _Label(HeaderLabel());

                do_exp(ptr, 1);

                free(buf);
                return;
        }

        // terminate while block
        else if (NF == 1 && strcmp(S[1], "endwhile") == 0)
        {
                if (!Level || BlockType[Level] != BWHILE)
                {
                        error("Error   %s %d : 'endwhile' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }
                
                setpagenum(StartPage[Level]);
                _JMP(HeaderLabel());
                _Label(EndLabel());
                synch_datapage();       // here we don't care about where we
                                        // are at the very moment - only
                                        // what happened to EXP and data pages
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'COUNT FROM'... construct
        else if (NF == 5 && strcmp(S[1], "count") == 0 && 
                            strcmp(S[2], "from") == 0 &&
                            strcmp(S[4], "=") == 0)
                            {
                if (find_reg(S[3]) < 0 && find_low_reg(S[3]) < 0)
                {
                        Undefined(S[3]);
                        free(buf);
                        return;
                }

                Level++;
                Sequence[Level]++;
                BlockType[Level] = BCOUNT;

                // remember variable type
                if (find_low_reg(S[3]) >= 0)
                {
                        CountVariable[Level] = find_low_reg(S[3]);
                        CVtypeWord[Level] = 1;
                }
                else
                {
                        CountVariable[Level] = find_reg(S[3]);
                        CVtypeWord[Level] = 0;
                }

                if (strlen(S[3]) + strlen(S[5]) + 3 > L_FLDLEN)
                {
                        error("Error   %s %d : Line too long\n", INFILE, NR);
                        strcpy(S[5], "0");
                }
                
                // correct high byte of constant for quick downcount
                if (CVtypeWord[Level] && isdigit(S[5][0]))
                {
                        if ((unsigned)get_value(S[5]) > (unsigned)(65535 - 256))
                        {
                                error("Error   %s %d : Start value must be <= %u\n", INFILE, NR, (unsigned)(65535 - 256));
                        }
                        sprintf(buf, "%s = %u", S[3], (unsigned)get_value(S[5]) + 256);
                }
                else
                {
                        strcpy(buf, S[3]);
                        strcat(buf, " = ");
                        strcat(buf, S[5]);
                }
                        
                if (!set_equal(buf))
                {
                        free(buf);
                        return;
                }

                // correct variable high byte for quick downcount
                if (CVtypeWord[Level] && !isdigit(S[5][0]))
                {
                        setpageval(CountVariable[Level]);
                        Opcode("incf", CountVariable[Level] - 1, 1, "");
                }

                _Label(StartLabel());
                reset_datapage();       // we will get here from EXP !!!
                free(buf);
                return;
        }

        // terminate COUNT-FROM block
        else if (NF == 1 && strcmp(S[1], "nextcount") == 0)
        {
                if (!Level || BlockType[Level] != BCOUNT)
                {
                        error("Error   %s %d : 'nextcount' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }

                StartPage[Level] = datapagenum;         
                setpageval(CountVariable[Level]);
                if (CVtypeWord[Level])
                {
                        Opcode("decfsz", CountVariable[Level], 1, "");
                        Opcode("goto", 0, 0, StartLabel());
                        Opcode("decfsz", CountVariable[Level] - 1, 1, "");
                        Opcode("goto", 0, 0, StartLabel());
                }
                else
                {
                        Opcode("decfsz", CountVariable[Level], 1, "");
                        Opcode("goto", 0, 0, StartLabel());
                }
                setpagenum(StartPage[Level]);
                
                _Label(EndLabel());
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'REPEAT'... construct
        else if (NF == 1 && strcmp(S[1], "repeat") == 0)
        {
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BREPEAT;
                _Label(StartLabel());
                reset_datapage();       // we will get here from EXP !!!
                free(buf);
                return;
        }

        // terminate REPEAT-UNTIL block
        else if (NF > 1 && strcmp(S[1], "until") == 0)
        {
                if (!Level || BlockType[Level] != BREPEAT)
                {
                        error("Error   %s %d : 'until' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }
                
                ptr = strstr(S[0], "until");
                ptr = strchr(ptr, ' ');
                while (isspace(*ptr)) ptr++;
                
                do_exp(ptr, 1);
                
                _Label(EndLabel());
                synch_datapage();
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'FOR'... construct
        else if (NF == 6 && strcmp(S[1], "for") == 0 && strcmp(S[NF-1], "to") == 0)
        {
                if (find_reg(S[2]) < 0 && find_low_reg(S[2]) < 0)
                {
                        Undefined(S[2]);
                        free(buf);
                        return;
                }

                strcpy(buf, S[2]);
                if (strlen(buf) + strlen(S[4]) + 3 > L_FLDLEN)
                {
                        error("Error   %s %d : Line too long\n", INFILE, NR);
                        free(buf);
                        return;
                }
                strcat(buf, " = ");
                strcat(buf, S[4]);
                if (!set_equal(buf))
                {
                        free(buf);
                        return;
                }

                strcpy(p_src, S[2]);
                if (S[6][0] == '&' && (addr = find_reg(&S[6][1])) >= 0)
                        sprintf(p_dst, "%d", addr);
                else if (S[6][0] == '&' && (addr = find_low_reg(&S[6][1])) >= 0)
                        sprintf(p_dst, "%d", addr);
                else
                        strcpy(p_dst, S[6]);

                Level++;
                Sequence[Level]++;
                BlockType[Level] = BFOR;
                StartPage[Level] = datapagenum; // note where we are
                _Label(StartLabel());

                strcpy(ForVar[Level], p_src);
                ForInc[Level] = 1;
                
                if (isdigit(S[6][0]))
                {
                        val = get_value(S[6]);
                        if (find_reg(S[2]) >= 0 && val == 255)
                        {
                                error("Error   %s %d : For optimisation: End value must be < 255\n", INFILE, NR);
                                free(buf);
                                return;
                        }
                        else if (find_low_reg(S[2]) >= 0 && val == 65535)
                        {
                                error("Error   %s %d : For optimisation: End value must be < 65535\n", INFILE, NR);
                                free(buf);
                                return;
                        }
                        sprintf(p_dst, "%u", val + 1);
                        do_operator(EQUAL, False);
                }
                else
                        do_operator(GREATER, False);
                
                free(buf);
                return;
        }

        // Do 'FOR...STEP'... construct
        else if (NF == 8 && strcmp(S[1], "for") == 0 && 
                 strcmp(S[NF-3], "to") == 0 && strcmp(S[NF-1], "step") == 0)
                 {
                if (find_reg(S[2]) < 0)
                {
                        Undefined(S[2]);
                        free(buf);
                        return;
                }

                strcpy(buf, S[2]);
                if (strlen(buf) + strlen(S[4]) + 3 > L_FLDLEN)
                {
                        error("Error   %s %d : Line too long\n", INFILE, NR);
                        free(buf);
                        return;
                }
                strcat(buf, " = ");
                strcat(buf, S[4]);
                if (!set_equal(buf))
                {
                        free(buf);
                        return;
                }

                strcpy(p_src, S[2]);
                if (S[6][0] == '&' && (addr = find_reg(&S[6][1])) >= 0)
                        sprintf(p_dst, "%d", addr);
                else
                        strcpy(p_dst, S[6]);

                Level++;
                Sequence[Level]++;
                BlockType[Level] = BFOR;
                StartPage[Level] = datapagenum; // note where we are
                _Label(StartLabel());

                strcpy(ForVar[Level], p_src);
                ForInc[Level] = get_value(S[NF]);
                if (ForInc[Level] == 0)
                {
                        error("Error   %s %d : STEP value must be greater than 0\n", INFILE, NR, S[2]);
                        free(buf);
                        return;
                }
                
                if (isdigit(S[6][0]))
                {
                        val = get_value(S[6]);
                        if (val == 255)
                        {
                                error("Error   %s %d : For optimisation: End value must be < 255\n", INFILE, NR);
                                free(buf);
                                return;
                        }       
                        sprintf(p_dst, "%u", val + 1);
                        do_operator(EQUAL, False);
                }
                else
                        do_operator(GREATER, False);
                
                free(buf);
                return;
        }

        // terminate for-block
        else if (NF == 1 && strcmp(S[1], "next") == 0)
        {
                if (!Level || BlockType[Level] != BFOR)
                {
                        error("Error   %s %d : 'next' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }

                if (ForInc[Level] == 1)
                        gen_inc(ForVar[Level]);
                else
                {
                        sprintf(buf, "%s += %s", ForVar[Level], ForInc[Level]);
                        plus(buf);      // handles INC options as well
                }
                
                setpagenum(StartPage[Level]);
                _JMP(StartLabel());
                _Label(EndLabel());
                synch_datapage();       // here we don't care about where we
                                        // are at the very moment - only
                                        // what happened to EXP and data pages
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // Do 'LOOP'... construct
        else if (NF == 1 && strcmp(S[1], "loop") == 0)
        {
                Level++;
                Sequence[Level]++;
                BlockType[Level] = BLOOP;
                StartPage[Level] = datapagenum;
                _Label(StartLabel());
                free(buf);
                return;
        }

        // terminate LOOP-ENDLOOP block
        else if (NF == 1 && strcmp(S[1], "endloop") == 0)
        {
                if (!Level || BlockType[Level] != BLOOP)
                {
                        error("Error   %s %d : 'endloop' out of place\n", INFILE, NR);
                        free(buf);
                        return;
                }

                setpagenum(StartPage[Level]);
                _JMP(StartLabel());
                _Label(EndLabel());
                BlockType[Level] = BNONE;
                Level--;
                free(buf);
                return;
        }

        // process cpu-specifics
        _CPUspecifics();
        free(buf);
}

END()
{
        int i;

        for (i = 0; i < NextProc; i++)
        {
                if (!(ProcStatus[i] & PROC_EXIST))
                {
                        if (ProcCodeEnd[i] > 0)
                                error("Error   %s - : Procedure '%s' called but does not exist\n", INFILE, Proc[i]);
                        else if ((ProcStatus[i] & PROC_CALLED))
                                error("Error   %s - : Procedure '%s' called but does not exist\n", INFILE, Proc[i]);
//                              error("Error   %s - : Label '%s' may not be called from NITPIC level\n", INFILE, Proc[i]);
//                      else
// (necessary ?)                warning("Warning %s - : Label '%s' is called - ensure proper return\n", INFILE, Proc[i]);
                }
                else if (!(ProcStatus[i] & PROC_CALLED) && 
                         !(ProcStatus[i] & ASM_CALLED) && 
                         strcmp(Proc[i], "INT_handler") != 0)
                        warning("Warning %s: Procedure '%s' never called\n", INFILE, Proc[i]);
        }

        _Epilogue();
}

// if we are not on the start page OR the expression changed pages, reset
synch_datapage()
{
        if (datapagenum != StartPage[Level] || PageChanged[Level])
                reset_datapage();
}

do_exp(char *ptr, char rem_page)
{
        char *Next;

        // note where we are
        if (rem_page)
                StartPage[Level] = datapagenum;

        // reset for expression handling
        PageChanged[Level] = 0;         

        // take note of EXP data changes
        InsideExp = 1;
        
        // process OR-blocks
        ORflagHistory = No;
        // convert to lower case
        if (strnicmp(ptr, " or ", 4) == 0)
        {
                ptr[1] = 'o';
                ptr[2] = 'r';
        }
        while (strstr(ptr, " or "))
        {
                ORflag = Yes;
                ORflagHistory = Yes;
                Next = strstr(ptr, " or ");
                *Next = '\0';           // terminate current exp
                Next = strstr(Next+1, "or ") + 3;
                while (isspace(*Next)) Next++;
                do_and(ptr);
                ptr = Next;
        }
        ORflag = No;
        do_and(ptr);

        // if code contains OR, add start label
        // test for '&& ORflagHistory == Yes' taken out to have STARTlabel available for 'continue'
        if (BlockType[Level] != BREPEAT)
        {
                if (ORflagHistory || BlockType[Level] != BIFGOTO)
                {
                        _Label(StartLabel());
                        synch_datapage();       // EXP might have changed pages
                }
        }

        // Reset
        InsideExp = 0;
}

do_and(char *ptr)
{
        char *Next;
        char DoLabel = No;
        
        // convert to lower case
        if (strnicmp(ptr, " and ", 5) == 0)
        {
                ptr[1] = 'a';
                ptr[2] = 'n';
                ptr[3] = 'd';
        }
        while (strstr(ptr, " and "))
        {
                ANDflag = Yes;
                DoLabel = Yes;
                Next = strstr(ptr, " and ");
                *Next = '\0';           // terminate current exp
                Next = strstr(Next+1, "and ") + 3;
                while (isspace(*Next)) Next++;
                do_single(ptr);
                ptr = Next;
        }
        ANDflag = No;
        do_single(ptr);

        // if code contains OR, add OR label
        if (ORflag && DoLabel)
        {
                _Label(ORlabel());
                ORlabelCount++;
        }
}

setup_indirect(char *ptr, char *var)
{
        int addr;
        char *buf = new(L_FLDLEN);

        inside_copy(buf, var);
        if (buf[0] == '&' && (addr = find_reg(&buf[1])) >= 0)
                sprintf(ptr, "%d", addr);
        else
                strcpy(ptr, buf);
        free(buf);
}

do_single(char *ptr)
{
        char *buf = new(L_FLDLEN);
        char *buf2 = new(L_FLDLEN);
        char *bigbuf = new(L_FLDLEN * 5);
        char *next, *pnt, *var;
        char negative = 0;
        int addr;

        raw_copy(buf, ptr);     
        if ((next = strchr(ptr, ':')))
        {
                *next = '\0';
                inside_copy(p_src, ptr);        // p_src = file regs
                inside_copy(buf2, next+2);      // get SET/CLEAR keyword or '='
                if (buf2[0] == '=' || (buf2[0] == '!' && buf2[1] == '='))
                {
                        if (buf2[0] == '!')
                                negative = 1;
                        pnt = next + 2;
                        while (*pnt++ != '=');
                        inside_copy(buf2, pnt); // get second parameter
                        if (strcmp(buf2, "0") == 0 && negative == 0)
                                strcpy(buf2, "clear");
                        else if (strcmp(buf2, "0") == 0 && negative == 1)
                                strcpy(buf2, "set");
                        else if (strcmp(buf2, "1") == 0 && negative == 0)
                                strcpy(buf2, "set");
                        else if (strcmp(buf2, "1") == 0 && negative == 1)
                                strcpy(buf2, "clear");
                        else if ((pnt = strchr(buf2, ':')) != NULL)
                        {
                                p_bit1 = *(next+1);
                                *pnt = '\0';
                                pnt++;
                                p_bit2 = *pnt;
                                strcpy(p_dst, buf2);
                                if (negative)
                                        do_operator(BITCOMP, False);
                                else
                                        do_operator(BITCOMP, True);
                                free(buf);
                                free(buf2);
                                free(bigbuf);
                                return;
                        }
                        else
                        {
	                        error("Error   %s %d : Value '%s' may only be 0 or 1 (check your #defines)\n", INFILE, NR, buf2);
	                        free(buf);
	                        free(buf2);
	                        free(bigbuf);
	                        return;
                        }
                }
                next += 2;                      // move to SET/CLEAR keyword
                *next = '\0';
                inside_copy(p_dst, next-1);     // get bit value
                if (atoi(p_dst) > 7)
                {
                        error("Error   %s %d : Use only bits 0-7\n", INFILE, NR);
                        free(buf);
                        free(buf2);
                        free(bigbuf);
                        return;
                }
                test_vars();
                if (strcmp(buf2, "set") == 0)
                        do_operator(BITSET, True);
                else if (strcmp(buf2, "clear") == 0)
                        do_operator(BITSET, False);
                else
                        error("Error   %s %d : Expected: 'set' or 'clear'\n", INFILE, NR);
        }
        else if (strstr(ptr, "<>"))
        {
                error("Error   %s %d : Must use '!=' instead of '<>'\n", INFILE, NR);
        }
        else if ((next = strstr(ptr, "!=")))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 2;
                setup_indirect(p_dst, var);
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                        swap(p_src, p_dst);
                do_operator(EQUAL, False);
        }
        else if ((next = strstr(ptr, ">=")))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 2;
                setup_indirect(p_dst, var);
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                {
                        swap(p_src, p_dst);
                        do_operator(GREATER, False);
                }
                else
                {
                        do_operator(GREATEREQ, True);
                }
        }
        else if ((next = strstr(ptr, "<=")))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 2;
                setup_indirect(p_dst, var);
                swap(p_src, p_dst);     // so we only need to test for CARRY
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                {
                        swap(p_src, p_dst);
                        do_operator(GREATER, False);
                }
                else
                {
                        do_operator(GREATEREQ, True);
                }
        }
        else if ((next = strchr(ptr, '>')))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 1;
                setup_indirect(p_dst, var);
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                {
                        swap(p_src, p_dst);
                        do_operator(GREATEREQ, False);
                }
                else
                {
                        do_operator(GREATER, True);
                }
        }
        else if ((next = strchr(ptr, '<')))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 1;
                setup_indirect(p_dst, var);
                swap(p_src, p_dst);     // so we only need to test for CARRY
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                {
                        swap(p_src, p_dst);
                        do_operator(GREATEREQ, False);
                }
                else
                {
                        do_operator(GREATER, True);
                }
        }
        else if ((next = strchr(ptr, '=')))
        {
                *next = '\0';
                setup_indirect(p_src, ptr);
                var = next + 1;
                setup_indirect(p_dst, var);
                test_vars();
                if (is_proc(p_src) || (isdigit(p_src[0]) && !is_proc(p_dst)))
                        swap(p_src, p_dst);
                do_operator(EQUAL, True);
        }
        else
                error("Error   %s %d : Expression syntax error\n", INFILE, NR);

        free(buf);
        free(buf2);
        free(bigbuf);
}

do_operator(int Opcode, int Direction)
{
        if (BlockType[Level] == BIFGOTO && !ANDflag && !ORflagHistory)
        {
                gentest(Opcode, Direction, S[NF]);
        }
        else if (BlockType[Level] == BREPEAT)
        {
                if (ORflag)
                {           // more ORs to follow later
                        if (ANDflag)    // more ANDs to follow later
                                gentest(Opcode, !Direction, ORlabel());
                        else            // this is the last AND before an OR
                                gentest(Opcode, Direction, EndLabel());
                }
                else                    // this is the last AND altogether
                        gentest(Opcode, !Direction, StartLabel());
        }
        else
        {
                if (ORflag)
                {           // more ORs to follow later
                        if (ANDflag)    // more ANDs to follow later
                                gentest(Opcode, !Direction, ORlabel());
                        else            // this is the last AND before an OR
                                gentest(Opcode, Direction, StartLabel());
                }
                else                    // this is the last AND altogether
                        gentest(Opcode, !Direction, EndLabel());
        }
}

gentest(int Opcode, int Direction, char *ENDlabel)
{
        switch (Opcode)
        {
                case EQUAL:             _JE(Direction, ENDlabel); break;
                case GREATER:           _JG(Direction, ENDlabel); break;
                case GREATEREQ:         _JGE(Direction, ENDlabel); break;
                case BITSET:            _JBITSET(Direction, ENDlabel); break;
                case BITCOMP:           _JBITCOMP(Direction, ENDlabel); break;
                default:                error("Error   %s %d : Invalid operator\n", INFILE, NR);
        }
}

terminate_if_group()
{
        if (BusyWithELSE[Level] == Yes)
        {
                BusyWithELSE[Level] = No;
                _Label(IF_ELSE_ENDlabel());
                IEElabelCount[Level]++;
        }
        synch_datapage();
}

raw_copy(char *dst, char *src)
{
        while (*src && isspace(*src)) src++;    // skip spaces
        while (*src)
        {
                if (!isspace(*src))
                        *dst++ = *src;
                src++;
        }
        *dst = '\0';
}

inside_copy(char *dst, char *src)
{
        while (*src && isspace(*src)) src++;    // skip spaces
        while (*dst++ = *src++);                // copy while not end
        dst -= 2;
        while (*dst && isspace(*dst)) dst--;    // remove back spaces
        dst++;
        *dst = '\0';                            // terminate
}

// process defines on the current line 
do_defines()
{
        char *ptr;
        int i, repeat;
        char DidDefine = 0;

        // get the tokens out
        fracture();
        // replace where needed
        for (i = 0; i < NextDef; i++)
        {
                for (repeat = 1; repeat <= NF; repeat++)
                {
                        // simple token replacement
                        if (strcmp(S[repeat], DefName[i]) == 0)
                        {
                                strcpy(S[repeat], Define[i]);
                                rebuild();
                                DidDefine = 1;
                        }
                        else
                        {
                                if ((ptr = strstr(S[repeat], DefName[i])) && 
                                    !islegal(*(ptr-1)) && !islegal(*(ptr+strlen(DefName[i]))))
                                    {
                                        replace(ptr, DefName[i], Define[i]);
                                        rebuild();
                                        DidDefine = 1;
                                }
                        }
                }
        }
        return(DidDefine);
}

// process macros on the current line 
do_macros()
{
        int i, j, k, Left, Right, r;
        char *trip, *start, *skip, *tstr;

        for (i = 0; i < NextMac; i++)
        {
                if ((tstr = strstr(S[0], MacName[i])) && 
                    !islegal(*(tstr-1)) && !islegal(*(tstr+strlen(MacName[i]))))
                    {
        
                        // macro found - so fracture
                        fracture();
        
                        // find left-right indexes
                        Right = Left = 0;
                        for (j = 1; j <= NF; j++)
                        {
                                if (strcmp(S[j], MacName[i]) == 0)
                                {
                                        Right = j;
                                        Left = j - 1;
                                        break; 
                                }
                        }
        
                        // remove the macro name and tokenise again
                        for (k = 0; k < strlen(MacName[i]); k++)
                                tstr[k] = ' ';
                        fracture();
        
                        // look for each token in succession
                        skip = S[0];
                        *skip = '\0';
                        start = Macro[i];
                        while ((trip = strchr(start, TRIPCHAR)))
                        {
        
                                // copies token-less part from macro
                                if (strlen(skip) + strlen(start) > L_FLDLEN)
                                {
                                        error("Error   %s %d : Line too long\n", INFILE, NR);
                                        return(0);
                                }
                                strncat(skip, start, trip - start);
        
                                // convert the parameter
                                trip++;
                                if (*trip == '-' && Left > 0)
                                        strcat(skip, S[Left]);
                                else if (*trip == '+' && Right > 0)
                                        strcat(skip, S[Right]);
                                else if (*trip >= '0' && *trip <= '9')
                                {
                                        j = *trip - '0' + 1;
                                        if (j <= NF)
                                                strcat(skip, S[*trip - '0' + 1]);
                                        else
                                        {
                                                error("Error   %s %d : Undetermined macro parameter '%c%c'\n", INFILE, NR, TRIPCHAR, *trip);
                                                return(0);
                                        }
                                }
        
                                // find next start
                                start = trip + 1;
                        }
        
                        // copy the remainder
                        if (strlen(skip) + strlen(start) > L_FLDLEN)
                        {
                                error("Error   %s %d : Line too long\n", INFILE, NR);
                                return(0);
                        }
                        strcat(skip, start);
                        
                        // fracture into tokens again
                        fracture();
                        return(1);
                }
        }
        return(0);
}

swap(char *one, char *two)
{
        char *buf = new(L_FLDLEN);
        strcpy(buf, two);
        strcpy(two, one);
        strcpy(one, buf);
        free(buf);
}

test_vars()
{
        // no 2 numerics
        if (isdigit(p_src[0]) && isdigit(p_dst[0]))
        {
                error("Error   %s %d : Only ONE operand may be a numeric constant\n", INFILE, NR);
                return;
        }

        // no 2 procs
        if (is_proc(p_src) && is_proc(p_dst))
        {
                error("Error   %s %d : Only ONE operand may be a procedure call\n", INFILE, NR);
                return;
        }

        // no type mixing allowed
        if ((find_reg(p_src) >= 0 && find_low_reg(p_dst) >= 0) || 
            (find_low_reg(p_src) >= 0 && find_reg(p_dst) >= 0))
            {
                MayNotMix();
                return;
        }

        // no words with procedures
        if ((is_proc(p_src) && find_low_reg(p_dst) >= 0) || 
            (find_low_reg(p_src) >= 0 && is_proc(p_dst)))
            {
                ProcToBytes();
                return;
        }

        // make sure the variables exist
        if (!isdigit(p_src[0]) && !is_proc(p_src) && find_reg(p_src) < 0 &&
            find_low_reg(p_src) < 0)
                give_error(p_src);
        if (!isdigit(p_dst[0]) && !is_proc(p_dst) && find_reg(p_dst) < 0 &&
            find_low_reg(p_dst) < 0)
                give_error(p_dst);
}

give_error(char *ptr)
{
        if (strpbrk(ptr, "0123456789") || toupper(ptr[strlen(ptr)-1]) == 'H')
                error("Error   %s %d : Definition error in '%s'\n", INFILE, NR, ptr);
        else
                Undefined(ptr);
}

// returns 1 if 'name' in '#define' list, alse 0
find_selection(char *name)
{
        int i;
                
        // run through DEFINE list
        for (i = 0; i < NextDef; i++)
        {
                if (strcmp(name, DefName[i]) == 0)
                        return(1);
        }
        return(0);
}
/******************************************************************************
                             End of PROCESS.C
******************************************************************************/