/******************************************************************************
  
      Filename   : SORT.H
      Program    : *** General ***
  
      Description: Prototypes for functions in SORT.OBJ
  
      Last edit  : July 24, 1992 [10:16:20]
  
      Date              Detail                      Author
      July 9, 1992      Created                     MH
  
******************************************************************************/

void StringSort(Byte *List[], Int Count);
